project:
  type: book

book:
  title: "DP-Next Data Management Plan"
  site-url: "https://dp-next.github.io/wp3-d-clin-dmp/"
  repo-url: "https://github.com/dp-next/wp3-d-clin-dmp"
  author:
    - name: "David Vadsholt"
      affiliation: "Steno Diabetes Center North"
      orcid: "0009-0005-6227-7333"
    - name: "Kristiane Beicher"
      affiliation: "Steno Diabetes Center Aarhus"
      orcid: "0000-0001-7556-9566"
  repo-branch: main
  repo-actions: [issue, edit, source]
  search:
    type: textbox
  downloads: [pdf]
  chapters:
    - index.qmd
    - part: "Sections"
      chapters:
      - sections/sources.qmd
      - sections/collection.qmd
      - sections/metadata.qmd
      - sections/ethics.qmd
      - sections/storage.qmd
      - sections/selection.qmd
      - sections/sharing.qmd
      - sections/responsibilities.qmd
    - part: "Supplementals"
      chapters:
        - supplemental/naming.qmd
        - supplemental/weeks-visits.qmd
        - supplemental/risk-assessment.qmd
  tools:
    - icon: github
      href: "https://github.com/dp-next/wp3-d-clin-dmp"
      aria-label: "GitHub icon: Source repository"
  page-footer:
    center:
      - text: "Licensed under CC BY 4.0"
        href: "LICENSE.md"

format:
  # TODO: Use Quarto extension if available
  html:
    theme:
      # TODO: Choose a different theme if desired
      - litera
      - custom-styles.scss
