project:
  type: dp-next-theme

book:
  title: "Clinical study DMP"
  site-url: "https://dp-next.github.io/wp3-d-clin-dmp/"
  repo-url: "https://github.com/dp-next/wp3-d-clin-dmp"
  author:
    - name: "Kristiane Beicher"
      affiliation: "Steno Diabetes Center Aarhus"
      orcid: "https://orcid.org/0000-0001-7556-9566"
    - name: "Luke W. Johnston"
      affiliation: "Steno Diabetes Center Aarhus"
      orcid: "https://orcid.org/0000-0003-4169-2616"
    - name: "David Vadsholt"
      affiliation: "Steno Diabetes Center North Jutland"
      orcid: "https://orcid.org/0009-0005-6227-7333"
  repo-branch: main
  repo-actions: [issue, edit, source]
  search:
    location: navbar
    type: textbox
  chapters:
    - index.qmd
    - part: "Sections"
      chapters:
      - ethics.qmd
      - storage.qmd
  # appendices:
  #  - path/to/file.qmd
  tools:
    - icon: github
      href: "https://github.com/dp-next/wp3-d-clin-dmp"
      aria-label: "GitHub icon: Source repository"
    - icon: house
      href: "https://dp-next.github.io"
      aria-label: "House icon: Main website for the DP-Next project"
  page-footer:
    center:
      - text: "Licensed under CC BY 4.0"
        href: "LICENSE.md"

format: dp-next-theme-html
