# Data sharing {#sec-sharing}

Sharing data from research projects is essential for promoting transparency,
reproducibility, and collaboration within the scientific community. By making
data findable, accessible, interoperable, and reusable (FAIR), we enable other
researchers to build upon existing work, validate and verify findings, and
generate new insights. This section outlines how data and metadata from the
project will be shared, under what conditions, and with what safeguards in
place.

## How will the data and metadata be shared?

We will make the metadata describing the structure, variables, and scope of the
dataset publicly available through one of our project websites, using [Seedcase
software](https://seedcase-project.org/) to build and structure it. This will
allow researchers (internal and external) to explore the metadata before
submitting an access request. The actual research data will not be publicly
accessible and will only be shared upon formal application and approval, and
only through a secure server.

## When will the metadata be available?

We aim to start metadata publication as soon as data collection starts.

## Who is the audience for the data?

We anticipate that most data access requests will come from researchers
affiliated with the study or collaborating institutions. However, external
researchers may also apply, provided they meet the criteria outlined in the data
access guideline. The audience may include clinical researchers,
epidemiologists, or data scientists researching diabetes-related topics, as well
as anthropologist or other social scientists interested in prediabetes.

## How will researchers get access to the data?

Researchers must submit a formal application detailing their planned use of the
data, including which specific data points they require and why. Applications
involving sensitive data categories must include a clear justification for their
necessity (for instance in cases where the data is to be uploaded to Denmark
Statistics). We will develop a guide on the application process, including
eligibility criteria and review procedures and that we will make available as a
website.

## How will the data be made available?

Once the steering committee has approved an application, we'll make the
requested data available in a dedicated project folder on
[GenomeDK](https://genome.au.dk) (GDK). Raw data must remain on the GDK server,
and only analysis scripts and results may be exported. Researchers will need to
create an account with GDK to access the folder and work on their analysis
environment. In some cases, it may be possible to upload a dataset to
[Statistics Denmark](https://www.dst.dk/en), under the SCDA Statistics Denmark
project database. We only consider this option for projects requiring linkage
with other national datasets.

## How will access be controlled?

There are three main ways to access data, and only one is used for data
analysis. Data will be available to a few members of the study team on REDCap
where we do data collection. All data collected by the Fitrockr app will only be
accessible to relevant personnel responsible for managing and transferring the
data to GDK. Finally, the research data we have collected, cleaned, and stored
on GDK servers will be analysed either on GDK servers or Statistics Denmark's
secure research environment. Access to the finalised research data will be
controlled by the central study team on GDK, with each successful data
application getting their own project folder with only the data requested. All
the programming scripts used to create these data sets will be stored in the
main study folder on GDK to ensure transparency and reproducibility. We expect
that those who have access to the data collected within REDCap will not use the
data for analysis and/or publication.
